spring:
  datasource:
    url: jdbc:sqlserver://localhost:61061;encrypt=false;trustServerCertificate=true;databaseName=servi_ot
    username: sa
    password: Clave01.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  mail:
    host: smtp.gmail.com           # Servidor SMTP
    port: 587                      # Puerto para TLS
    username: servios355@gamail.com   # Tu correo electrónico
    password: Rodney$1975.         # La contraseña de tu correo
    properties:
      mail:
        smtp:
          auth: true               # Habilitar autenticación SMTP
          starttls:
            enable: true           # Habilitar STARTTLS (para TLS)
